# Generated by Django 4.1.5 on 2023-01-26 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='accepted',
        ),
    ]
