# Generated by Django 4.1.5 on 2023-01-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0016_alter_attendance_login_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='end_break',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_break',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
