# Generated by Django 3.2.16 on 2023-01-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0018_auto_20230127_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approver',
        ),
    ]
