# Generated by Django 3.2.16 on 2023-01-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0019_delete_approver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employer',
        ),
    ]
