# Generated by Django 4.1.5 on 2023-01-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0021_remove_employer_company_company_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employer',
        ),
        migrations.AddField(
            model_name='company',
            name='employer',
            field=models.ManyToManyField(blank=True, null=True, to='snippets.employer'),
        ),
    ]
