# Generated by Django 4.1.5 on 2023-01-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0022_remove_company_employer_company_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approver',
            name='company',
        ),
        migrations.RemoveField(
            model_name='approver',
            name='owner',
        ),
    ]
