# Generated by Django 3.2.16 on 2023-01-28 18:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0023_employee_deisgnation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.AddField(
            model_name='attendance',
            name='company',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='break_end',
            field=models.TimeField(default='13:45:00'),
        ),
        migrations.AlterField(
            model_name='company',
            name='break_start',
            field=models.TimeField(default='13:00:00'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='employer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='snippets.employer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='login_time',
            field=models.TimeField(default='9:00:00'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logout_time',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.employer'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippets.company'),
        ),
    ]
